[package]
name = "geo_primitives"
version = "0.1.0"
edition = "2021"

[dependencies]
geo_core = { path = "../geo_core" }

[features]
default = []
serde = ["dep:serde"]

[dependencies.serde]
version = "1.0.228"
features = ["derive"]
optional = true
