[package]
name = "redring"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "26.0.1"
winit = "0.30.12"      # ウィンドウ管理
pollster = "0.4.0"    # 非同期初期化でよく使う

viewmodel = { path = "../viewmodel" }
model = { path = "../model" }