[package]
name = "redring"
version = "0.1.0"
edition = "2021"
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
winit = "0.30.13"
wgpu = "29.0.1"
smol_str = "0.3.2"
pollster.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-appender = "0.2"
viewmodel = { path = "../../viewmodel/converter" }
viewmodel-graphics = { path = "../../viewmodel/graphics" }
render = { path = "../render" }
stage = { path = "../stage" }
analysis = { path = "../../foundation/analysis" }
logging_foundation = { path = "../../foundation/logging_foundation" }
bytemuck = { version = "1.24", features = ["derive"] }
egui = "0.34.1"
egui-wgpu = "0.34.1"
egui-winit = "0.34.1"
fontdb = "0.23"
