[package]
name = "geo_algorithms"
version = "0.1.0"
edition = "2021"

[dependencies]
analysis = { path = "../../foundation/analysis" }
geo_contracts = { path = "../geo_contracts" }
geo_primitives = { path = "../geo_primitives" }
geo_topology = { path = "../geo_topology" }
geo_nurbs = { path = "../geo_nurbs" }
geo_core = { path = "../geo_core" }
rayon = "1.10"

