[package]
name = "geo_algorithms"
version = "0.1.0"
edition = "2021"

[dependencies]
analysis = { path = "../../foundation/analysis" }
geo_foundation = { path = "../geo_foundation" }
geo_primitives = { path = "../geo_primitives" }
geo_nurbs = { path = "../geo_nurbs" }
geo_core = { path = "../geo_core" }
geo_commons = { path = "../geo_commons" }
