[package]
name = "render"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.30"
wgpu = "27.0.1"
tracing = "0.1"
bytemuck = "1.23.2"
pollster.workspace = true
geo_primitives = { path = "../geo_primitives" }
geo_foundation = { path = "../geo_foundation" }
