use super::{Cardinality, Dimension, MatrixEntry, Operation};

pub(super) fn entries() -> Vec<MatrixEntry> {
    vec![
        MatrixEntry {
            id: "2d:circle-ray:intersection",
            dimension: Dimension::D2,
            operation: Operation::Intersection,
            shape_a: "Circle2D",
            shape_b: "Ray2D",
            required: true,
            symmetric: true,
            cardinality: Some(Cardinality::Multiple),
            entrypoint_a_to_b: Some("circle2d_ray2d_intersections"),
            entrypoint_b_to_a: Some("ray2d_circle2d_intersections"),
        },
        MatrixEntry {
            id: "2d:ray-circle:intersection",
            dimension: Dimension::D2,
            operation: Operation::Intersection,
            shape_a: "Ray2D",
            shape_b: "Circle2D",
            required: true,
            symmetric: true,
            cardinality: Some(Cardinality::Multiple),
            entrypoint_a_to_b: Some("ray2d_circle2d_intersections"),
            entrypoint_b_to_a: Some("circle2d_ray2d_intersections"),
        },
        MatrixEntry {
            id: "2d:segment-ray:intersection",
            dimension: Dimension::D2,
            operation: Operation::Intersection,
            shape_a: "LineSegment2D",
            shape_b: "Ray2D",
            required: true,
            symmetric: true,
            cardinality: Some(Cardinality::Single),
            entrypoint_a_to_b: Some("line_segment2d_ray2d_intersection"),
            entrypoint_b_to_a: Some("ray2d_line_segment2d_intersection"),
        },
        MatrixEntry {
            id: "2d:ray-segment:intersection",
            dimension: Dimension::D2,
            operation: Operation::Intersection,
            shape_a: "Ray2D",
            shape_b: "LineSegment2D",
            required: true,
            symmetric: true,
            cardinality: Some(Cardinality::Single),
            entrypoint_a_to_b: Some("ray2d_line_segment2d_intersection"),
            entrypoint_b_to_a: Some("line_segment2d_ray2d_intersection"),
        },
        MatrixEntry {
            id: "2d:circle-ellipse:intersection",
            dimension: Dimension::D2,
            operation: Operation::Intersection,
            shape_a: "Circle2D",
            shape_b: "Ellipse2D",
            required: true,
            symmetric: true,
            cardinality: Some(Cardinality::Optional),
            entrypoint_a_to_b: Some("circle2d_ellipse2d_intersection"),
            entrypoint_b_to_a: Some("ellipse2d_circle2d_intersection"),
        },
        MatrixEntry {
            id: "2d:ellipse-circle:intersection",
            dimension: Dimension::D2,
            operation: Operation::Intersection,
            shape_a: "Ellipse2D",
            shape_b: "Circle2D",
            required: true,
            symmetric: true,
            cardinality: Some(Cardinality::Optional),
            entrypoint_a_to_b: Some("ellipse2d_circle2d_intersection"),
            entrypoint_b_to_a: Some("circle2d_ellipse2d_intersection"),
        },
        MatrixEntry {
            id: "2d:line-circle:intersection",
            dimension: Dimension::D2,
            operation: Operation::Intersection,
            shape_a: "InfiniteLine2D",
            shape_b: "Circle2D",
            required: true,
            symmetric: true,
            cardinality: Some(Cardinality::Multiple),
            entrypoint_a_to_b: Some("infinite_line2d_circle2d_intersections"),
            entrypoint_b_to_a: Some("circle2d_infinite_line2d_intersections"),
        },
        MatrixEntry {
            id: "2d:circle-line:intersection",
            dimension: Dimension::D2,
            operation: Operation::Intersection,
            shape_a: "Circle2D",
            shape_b: "InfiniteLine2D",
            required: true,
            symmetric: true,
            cardinality: Some(Cardinality::Multiple),
            entrypoint_a_to_b: Some("circle2d_infinite_line2d_intersections"),
            entrypoint_b_to_a: Some("infinite_line2d_circle2d_intersections"),
        },
        MatrixEntry {
            id: "2d:line-segment:intersection",
            dimension: Dimension::D2,
            operation: Operation::Intersection,
            shape_a: "InfiniteLine2D",
            shape_b: "LineSegment2D",
            required: true,
            symmetric: true,
            cardinality: Some(Cardinality::Optional),
            entrypoint_a_to_b: Some("infinite_line2d_line_segment2d_intersection"),
            entrypoint_b_to_a: Some("line_segment2d_infinite_line2d_intersection"),
        },
        MatrixEntry {
            id: "2d:segment-line:intersection",
            dimension: Dimension::D2,
            operation: Operation::Intersection,
            shape_a: "LineSegment2D",
            shape_b: "InfiniteLine2D",
            required: true,
            symmetric: true,
            cardinality: Some(Cardinality::Optional),
            entrypoint_a_to_b: Some("line_segment2d_infinite_line2d_intersection"),
            entrypoint_b_to_a: Some("infinite_line2d_line_segment2d_intersection"),
        },
        MatrixEntry {
            id: "2d:line-ray:intersection",
            dimension: Dimension::D2,
            operation: Operation::Intersection,
            shape_a: "InfiniteLine2D",
            shape_b: "Ray2D",
            required: true,
            symmetric: true,
            cardinality: Some(Cardinality::Optional),
            entrypoint_a_to_b: Some("infinite_line2d_ray2d_intersection"),
            entrypoint_b_to_a: Some("ray2d_infinite_line2d_intersection"),
        },
        MatrixEntry {
            id: "2d:ray-line:intersection",
            dimension: Dimension::D2,
            operation: Operation::Intersection,
            shape_a: "Ray2D",
            shape_b: "InfiniteLine2D",
            required: true,
            symmetric: true,
            cardinality: Some(Cardinality::Optional),
            entrypoint_a_to_b: Some("ray2d_infinite_line2d_intersection"),
            entrypoint_b_to_a: Some("infinite_line2d_ray2d_intersection"),
        },
        MatrixEntry {
            id: "2d:triangle-segment:intersections",
            dimension: Dimension::D2,
            operation: Operation::Intersection,
            shape_a: "Triangle2D",
            shape_b: "LineSegment2D",
            required: true,
            symmetric: false,
            cardinality: Some(Cardinality::Multiple),
            entrypoint_a_to_b: Some("triangle2d_line_segment2d_intersections"),
            entrypoint_b_to_a: None,
        },
    ]
}
