use super::{Dimension, MatrixEntry, Operation};

pub(super) fn entries() -> Vec<MatrixEntry> {
    vec![
        MatrixEntry {
            id: "2d:circle-ray:collision",
            dimension: Dimension::D2,
            operation: Operation::Collision,
            shape_a: "Circle2D",
            shape_b: "Ray2D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("circle2d_ray2d_collides"),
            entrypoint_b_to_a: Some("ray2d_circle2d_collides"),
        },
        MatrixEntry {
            id: "2d:ray-circle:collision",
            dimension: Dimension::D2,
            operation: Operation::Collision,
            shape_a: "Ray2D",
            shape_b: "Circle2D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("ray2d_circle2d_collides"),
            entrypoint_b_to_a: Some("circle2d_ray2d_collides"),
        },
        MatrixEntry {
            id: "2d:segment-ray:collision",
            dimension: Dimension::D2,
            operation: Operation::Collision,
            shape_a: "LineSegment2D",
            shape_b: "Ray2D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("line_segment2d_ray2d_collides"),
            entrypoint_b_to_a: Some("ray2d_line_segment2d_collides"),
        },
        MatrixEntry {
            id: "2d:ray-segment:collision",
            dimension: Dimension::D2,
            operation: Operation::Collision,
            shape_a: "Ray2D",
            shape_b: "LineSegment2D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("ray2d_line_segment2d_collides"),
            entrypoint_b_to_a: Some("line_segment2d_ray2d_collides"),
        },
        MatrixEntry {
            id: "2d:arc-circle:collision",
            dimension: Dimension::D2,
            operation: Operation::Collision,
            shape_a: "Arc2D",
            shape_b: "Circle2D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("arc2d_circle2d_collides"),
            entrypoint_b_to_a: Some("circle2d_arc2d_collides"),
        },
        MatrixEntry {
            id: "2d:circle-arc:collision",
            dimension: Dimension::D2,
            operation: Operation::Collision,
            shape_a: "Circle2D",
            shape_b: "Arc2D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("circle2d_arc2d_collides"),
            entrypoint_b_to_a: Some("arc2d_circle2d_collides"),
        },
        MatrixEntry {
            id: "2d:segment-arc:collision",
            dimension: Dimension::D2,
            operation: Operation::Collision,
            shape_a: "LineSegment2D",
            shape_b: "Arc2D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("line_segment2d_arc2d_collides"),
            entrypoint_b_to_a: Some("arc2d_line_segment2d_collides"),
        },
        MatrixEntry {
            id: "2d:arc-segment:collision",
            dimension: Dimension::D2,
            operation: Operation::Collision,
            shape_a: "Arc2D",
            shape_b: "LineSegment2D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("arc2d_line_segment2d_collides"),
            entrypoint_b_to_a: Some("line_segment2d_arc2d_collides"),
        },
        MatrixEntry {
            id: "2d:triangle-circle:collision",
            dimension: Dimension::D2,
            operation: Operation::Collision,
            shape_a: "Triangle2D",
            shape_b: "Circle2D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("triangle2d_circle2d_collides"),
            entrypoint_b_to_a: Some("circle2d_triangle2d_collides"),
        },
        MatrixEntry {
            id: "2d:circle-triangle:collision",
            dimension: Dimension::D2,
            operation: Operation::Collision,
            shape_a: "Circle2D",
            shape_b: "Triangle2D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("circle2d_triangle2d_collides"),
            entrypoint_b_to_a: Some("triangle2d_circle2d_collides"),
        },
        MatrixEntry {
            id: "2d:triangle-segment:collision",
            dimension: Dimension::D2,
            operation: Operation::Collision,
            shape_a: "Triangle2D",
            shape_b: "LineSegment2D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("triangle2d_line_segment2d_collides"),
            entrypoint_b_to_a: Some("line_segment2d_triangle2d_collides"),
        },
        MatrixEntry {
            id: "2d:segment-triangle:collision",
            dimension: Dimension::D2,
            operation: Operation::Collision,
            shape_a: "LineSegment2D",
            shape_b: "Triangle2D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("line_segment2d_triangle2d_collides"),
            entrypoint_b_to_a: Some("triangle2d_line_segment2d_collides"),
        },
        MatrixEntry {
            id: "2d:line-circle:collision",
            dimension: Dimension::D2,
            operation: Operation::Collision,
            shape_a: "InfiniteLine2D",
            shape_b: "Circle2D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("infinite_line2d_circle2d_collides"),
            entrypoint_b_to_a: Some("circle2d_infinite_line2d_collides"),
        },
        MatrixEntry {
            id: "2d:circle-line:collision",
            dimension: Dimension::D2,
            operation: Operation::Collision,
            shape_a: "Circle2D",
            shape_b: "InfiniteLine2D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("circle2d_infinite_line2d_collides"),
            entrypoint_b_to_a: Some("infinite_line2d_circle2d_collides"),
        },
        MatrixEntry {
            id: "2d:line-segment:collision",
            dimension: Dimension::D2,
            operation: Operation::Collision,
            shape_a: "InfiniteLine2D",
            shape_b: "LineSegment2D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("infinite_line2d_line_segment2d_collides"),
            entrypoint_b_to_a: Some("line_segment2d_infinite_line2d_collides"),
        },
        MatrixEntry {
            id: "2d:segment-line:collision",
            dimension: Dimension::D2,
            operation: Operation::Collision,
            shape_a: "LineSegment2D",
            shape_b: "InfiniteLine2D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("line_segment2d_infinite_line2d_collides"),
            entrypoint_b_to_a: Some("infinite_line2d_line_segment2d_collides"),
        },
        MatrixEntry {
            id: "2d:line-ray:collision",
            dimension: Dimension::D2,
            operation: Operation::Collision,
            shape_a: "InfiniteLine2D",
            shape_b: "Ray2D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("infinite_line2d_ray2d_collides"),
            entrypoint_b_to_a: Some("ray2d_infinite_line2d_collides"),
        },
        MatrixEntry {
            id: "2d:ray-line:collision",
            dimension: Dimension::D2,
            operation: Operation::Collision,
            shape_a: "Ray2D",
            shape_b: "InfiniteLine2D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("ray2d_infinite_line2d_collides"),
            entrypoint_b_to_a: Some("infinite_line2d_ray2d_collides"),
        },
        MatrixEntry {
            id: "2d:ellipse-circle:collision",
            dimension: Dimension::D2,
            operation: Operation::Collision,
            shape_a: "Ellipse2D",
            shape_b: "Circle2D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("ellipse2d_circle2d_collides"),
            entrypoint_b_to_a: Some("circle2d_ellipse2d_collides"),
        },
        MatrixEntry {
            id: "2d:circle-ellipse:collision",
            dimension: Dimension::D2,
            operation: Operation::Collision,
            shape_a: "Circle2D",
            shape_b: "Ellipse2D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("circle2d_ellipse2d_collides"),
            entrypoint_b_to_a: Some("ellipse2d_circle2d_collides"),
        },
        MatrixEntry {
            id: "2d:ellipse_arc-circle:collision",
            dimension: Dimension::D2,
            operation: Operation::Collision,
            shape_a: "EllipseArc2D",
            shape_b: "Circle2D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("ellipse_arc2d_circle2d_collides"),
            entrypoint_b_to_a: Some("circle2d_ellipse_arc2d_collides"),
        },
        MatrixEntry {
            id: "2d:circle-ellipse_arc:collision",
            dimension: Dimension::D2,
            operation: Operation::Collision,
            shape_a: "Circle2D",
            shape_b: "EllipseArc2D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("circle2d_ellipse_arc2d_collides"),
            entrypoint_b_to_a: Some("ellipse_arc2d_circle2d_collides"),
        },
    ]
}
