use super::{Dimension, MatrixEntry, Operation};

pub(super) fn entries() -> Vec<MatrixEntry> {
    vec![
        MatrixEntry {
            id: "2d:segment-point:distance",
            dimension: Dimension::D2,
            operation: Operation::Distance,
            shape_a: "LineSegment2D",
            shape_b: "Point2D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("line_segment2d_point2d_distance"),
            entrypoint_b_to_a: Some("point2d_line_segment2d_distance"),
        },
        MatrixEntry {
            id: "2d:point-segment:distance",
            dimension: Dimension::D2,
            operation: Operation::Distance,
            shape_a: "Point2D",
            shape_b: "LineSegment2D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("point2d_line_segment2d_distance"),
            entrypoint_b_to_a: Some("line_segment2d_point2d_distance"),
        },
        MatrixEntry {
            id: "2d:infinite_line-point:distance",
            dimension: Dimension::D2,
            operation: Operation::Distance,
            shape_a: "InfiniteLine2D",
            shape_b: "Point2D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("infinite_line2d_point2d_distance"),
            entrypoint_b_to_a: Some("point2d_infinite_line2d_distance"),
        },
        MatrixEntry {
            id: "2d:point-infinite_line:distance",
            dimension: Dimension::D2,
            operation: Operation::Distance,
            shape_a: "Point2D",
            shape_b: "InfiniteLine2D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("point2d_infinite_line2d_distance"),
            entrypoint_b_to_a: Some("infinite_line2d_point2d_distance"),
        },
        MatrixEntry {
            id: "2d:ray-point:distance",
            dimension: Dimension::D2,
            operation: Operation::Distance,
            shape_a: "Ray2D",
            shape_b: "Point2D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("ray2d_point2d_distance"),
            entrypoint_b_to_a: Some("point2d_ray2d_distance"),
        },
        MatrixEntry {
            id: "2d:point-ray:distance",
            dimension: Dimension::D2,
            operation: Operation::Distance,
            shape_a: "Point2D",
            shape_b: "Ray2D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("point2d_ray2d_distance"),
            entrypoint_b_to_a: Some("ray2d_point2d_distance"),
        },
        MatrixEntry {
            id: "2d:circle-point:distance",
            dimension: Dimension::D2,
            operation: Operation::Distance,
            shape_a: "Circle2D",
            shape_b: "Point2D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("circle2d_point2d_distance"),
            entrypoint_b_to_a: Some("point2d_circle2d_distance"),
        },
        MatrixEntry {
            id: "2d:point-circle:distance",
            dimension: Dimension::D2,
            operation: Operation::Distance,
            shape_a: "Point2D",
            shape_b: "Circle2D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("point2d_circle2d_distance"),
            entrypoint_b_to_a: Some("circle2d_point2d_distance"),
        },
    ]
}
