use super::{Cardinality, Dimension, MatrixEntry, Operation};

pub(super) fn entries() -> Vec<MatrixEntry> {
    vec![
        MatrixEntry {
            id: "3d:line-segment:intersection",
            dimension: Dimension::D3,
            operation: Operation::Intersection,
            shape_a: "InfiniteLine3D",
            shape_b: "LineSegment3D",
            required: true,
            symmetric: false,
            cardinality: Some(Cardinality::Optional),
            entrypoint_a_to_b: Some("infinite_line3d_line_segment3d_intersection"),
            entrypoint_b_to_a: None,
        },
        MatrixEntry {
            id: "3d:line-ray:intersection",
            dimension: Dimension::D3,
            operation: Operation::Intersection,
            shape_a: "InfiniteLine3D",
            shape_b: "Ray3D",
            required: true,
            symmetric: true,
            cardinality: Some(Cardinality::Optional),
            entrypoint_a_to_b: Some("infinite_line3d_ray3d_intersection"),
            entrypoint_b_to_a: Some("ray3d_infinite_line3d_intersection"),
        },
        MatrixEntry {
            id: "3d:plane-segment:intersection",
            dimension: Dimension::D3,
            operation: Operation::Intersection,
            shape_a: "Plane3D",
            shape_b: "LineSegment3D",
            required: true,
            symmetric: false,
            cardinality: Some(Cardinality::Optional),
            entrypoint_a_to_b: Some("plane3d_line_segment3d_intersection"),
            entrypoint_b_to_a: None,
        },
        MatrixEntry {
            id: "3d:plane-ray:intersection",
            dimension: Dimension::D3,
            operation: Operation::Intersection,
            shape_a: "Plane3D",
            shape_b: "Ray3D",
            required: true,
            symmetric: false,
            cardinality: Some(Cardinality::Optional),
            entrypoint_a_to_b: Some("plane3d_ray3d_intersection"),
            entrypoint_b_to_a: None,
        },
        MatrixEntry {
            id: "3d:ray-line:intersection",
            dimension: Dimension::D3,
            operation: Operation::Intersection,
            shape_a: "Ray3D",
            shape_b: "InfiniteLine3D",
            required: true,
            symmetric: true,
            cardinality: Some(Cardinality::Optional),
            entrypoint_a_to_b: Some("ray3d_infinite_line3d_intersection"),
            entrypoint_b_to_a: Some("infinite_line3d_ray3d_intersection"),
        },
        MatrixEntry {
            id: "3d:triangle-segment:intersection",
            dimension: Dimension::D3,
            operation: Operation::Intersection,
            shape_a: "Triangle3D",
            shape_b: "LineSegment3D",
            required: true,
            symmetric: true,
            cardinality: Some(Cardinality::Optional),
            entrypoint_a_to_b: Some("triangle3d_line_segment3d_intersection"),
            entrypoint_b_to_a: Some("line_segment3d_triangle3d_intersection"),
        },
        MatrixEntry {
            id: "3d:segment-triangle:intersection",
            dimension: Dimension::D3,
            operation: Operation::Intersection,
            shape_a: "LineSegment3D",
            shape_b: "Triangle3D",
            required: true,
            symmetric: true,
            cardinality: Some(Cardinality::Optional),
            entrypoint_a_to_b: Some("line_segment3d_triangle3d_intersection"),
            entrypoint_b_to_a: Some("triangle3d_line_segment3d_intersection"),
        },
        MatrixEntry {
            id: "3d:triangle-ray:intersection",
            dimension: Dimension::D3,
            operation: Operation::Intersection,
            shape_a: "Triangle3D",
            shape_b: "Ray3D",
            required: true,
            symmetric: true,
            cardinality: Some(Cardinality::Optional),
            entrypoint_a_to_b: Some("triangle3d_ray3d_intersection"),
            entrypoint_b_to_a: Some("ray3d_triangle3d_intersection"),
        },
        MatrixEntry {
            id: "3d:ray-triangle:intersection",
            dimension: Dimension::D3,
            operation: Operation::Intersection,
            shape_a: "Ray3D",
            shape_b: "Triangle3D",
            required: true,
            symmetric: true,
            cardinality: Some(Cardinality::Optional),
            entrypoint_a_to_b: Some("ray3d_triangle3d_intersection"),
            entrypoint_b_to_a: Some("triangle3d_ray3d_intersection"),
        },
        MatrixEntry {
            id: "3d:line-line:intersection",
            dimension: Dimension::D3,
            operation: Operation::Intersection,
            shape_a: "InfiniteLine3D",
            shape_b: "InfiniteLine3D",
            required: true,
            symmetric: false,
            cardinality: Some(Cardinality::Optional),
            entrypoint_a_to_b: Some("infinite_line3d_infinite_line3d_intersection"),
            entrypoint_b_to_a: None,
        },
        MatrixEntry {
            id: "3d:segment-segment:intersection",
            dimension: Dimension::D3,
            operation: Operation::Intersection,
            shape_a: "LineSegment3D",
            shape_b: "LineSegment3D",
            required: true,
            symmetric: false,
            cardinality: Some(Cardinality::Optional),
            entrypoint_a_to_b: Some("line_segment3d_line_segment3d_intersection"),
            entrypoint_b_to_a: None,
        },
        MatrixEntry {
            id: "3d:ray-ray:intersection",
            dimension: Dimension::D3,
            operation: Operation::Intersection,
            shape_a: "Ray3D",
            shape_b: "Ray3D",
            required: true,
            symmetric: false,
            cardinality: Some(Cardinality::Optional),
            entrypoint_a_to_b: Some("ray3d_ray3d_intersection"),
            entrypoint_b_to_a: None,
        },
        MatrixEntry {
            id: "3d:cylindrical_surface-cylindrical_surface:intersection",
            dimension: Dimension::D3,
            operation: Operation::Intersection,
            shape_a: "CylindricalSurface3D",
            shape_b: "CylindricalSurface3D",
            required: true,
            symmetric: false,
            cardinality: Some(Cardinality::Optional),
            entrypoint_a_to_b: Some("cylindrical_surface3d_cylindrical_surface3d_intersection"),
            entrypoint_b_to_a: None,
        },
        MatrixEntry {
            id: "3d:conical_solid-point:intersection",
            dimension: Dimension::D3,
            operation: Operation::Intersection,
            shape_a: "ConicalSolid3D",
            shape_b: "Point3D",
            required: true,
            symmetric: false,
            cardinality: Some(Cardinality::Optional),
            entrypoint_a_to_b: Some("conical_solid3d_point3d_intersection"),
            entrypoint_b_to_a: None,
        },
        MatrixEntry {
            id: "3d:conical_solid-line:intersection",
            dimension: Dimension::D3,
            operation: Operation::Intersection,
            shape_a: "ConicalSolid3D",
            shape_b: "InfiniteLine3D",
            required: true,
            symmetric: false,
            cardinality: Some(Cardinality::Optional),
            entrypoint_a_to_b: Some("conical_solid3d_line3d_intersection"),
            entrypoint_b_to_a: None,
        },
        MatrixEntry {
            id: "3d:conical_solid-ray:intersection",
            dimension: Dimension::D3,
            operation: Operation::Intersection,
            shape_a: "ConicalSolid3D",
            shape_b: "Ray3D",
            required: true,
            symmetric: false,
            cardinality: Some(Cardinality::Optional),
            entrypoint_a_to_b: Some("conical_solid3d_ray3d_intersection"),
            entrypoint_b_to_a: None,
        },
        MatrixEntry {
            id: "3d:conical_solid-segment:intersection",
            dimension: Dimension::D3,
            operation: Operation::Intersection,
            shape_a: "ConicalSolid3D",
            shape_b: "LineSegment3D",
            required: true,
            symmetric: false,
            cardinality: Some(Cardinality::Optional),
            entrypoint_a_to_b: Some("conical_solid3d_line_segment3d_intersection"),
            entrypoint_b_to_a: None,
        },
        MatrixEntry {
            id: "3d:conical_solid-plane:intersection",
            dimension: Dimension::D3,
            operation: Operation::Intersection,
            shape_a: "ConicalSolid3D",
            shape_b: "Plane3D",
            required: true,
            symmetric: false,
            cardinality: Some(Cardinality::Optional),
            entrypoint_a_to_b: Some("conical_solid3d_plane3d_intersection"),
            entrypoint_b_to_a: None,
        },
        MatrixEntry {
            id: "3d:conical_surface-point:intersection",
            dimension: Dimension::D3,
            operation: Operation::Intersection,
            shape_a: "ConicalSurface3D",
            shape_b: "Point3D",
            required: true,
            symmetric: false,
            cardinality: Some(Cardinality::Optional),
            entrypoint_a_to_b: Some("conical_surface3d_point3d_intersection"),
            entrypoint_b_to_a: None,
        },
        MatrixEntry {
            id: "3d:conical_surface-line:intersection",
            dimension: Dimension::D3,
            operation: Operation::Intersection,
            shape_a: "ConicalSurface3D",
            shape_b: "InfiniteLine3D",
            required: true,
            symmetric: false,
            cardinality: Some(Cardinality::Multiple),
            entrypoint_a_to_b: Some("conical_surface3d_infinite_line3d_intersections"),
            entrypoint_b_to_a: None,
        },
        MatrixEntry {
            id: "3d:conical_surface-ray:intersection",
            dimension: Dimension::D3,
            operation: Operation::Intersection,
            shape_a: "ConicalSurface3D",
            shape_b: "Ray3D",
            required: true,
            symmetric: false,
            cardinality: Some(Cardinality::Multiple),
            entrypoint_a_to_b: Some("conical_surface3d_ray3d_intersections"),
            entrypoint_b_to_a: None,
        },
        MatrixEntry {
            id: "3d:conical_surface-segment:intersection",
            dimension: Dimension::D3,
            operation: Operation::Intersection,
            shape_a: "ConicalSurface3D",
            shape_b: "LineSegment3D",
            required: true,
            symmetric: false,
            cardinality: Some(Cardinality::Multiple),
            entrypoint_a_to_b: Some("conical_surface3d_line_segment3d_intersections"),
            entrypoint_b_to_a: None,
        },
        MatrixEntry {
            id: "3d:spherical_solid-point:intersection",
            dimension: Dimension::D3,
            operation: Operation::Intersection,
            shape_a: "SphericalSolid3D",
            shape_b: "Point3D",
            required: true,
            symmetric: false,
            cardinality: Some(Cardinality::Optional),
            entrypoint_a_to_b: Some("spherical_solid3d_point3d_intersection"),
            entrypoint_b_to_a: None,
        },
        MatrixEntry {
            id: "3d:spherical_solid-line:intersection",
            dimension: Dimension::D3,
            operation: Operation::Intersection,
            shape_a: "SphericalSolid3D",
            shape_b: "InfiniteLine3D",
            required: true,
            symmetric: false,
            cardinality: Some(Cardinality::Optional),
            entrypoint_a_to_b: Some("spherical_solid3d_line3d_intersection"),
            entrypoint_b_to_a: None,
        },
        MatrixEntry {
            id: "3d:spherical_solid-ray:intersection",
            dimension: Dimension::D3,
            operation: Operation::Intersection,
            shape_a: "SphericalSolid3D",
            shape_b: "Ray3D",
            required: true,
            symmetric: false,
            cardinality: Some(Cardinality::Optional),
            entrypoint_a_to_b: Some("spherical_solid3d_ray3d_intersection"),
            entrypoint_b_to_a: None,
        },
        MatrixEntry {
            id: "3d:segment-sphere:intersection",
            dimension: Dimension::D3,
            operation: Operation::Intersection,
            shape_a: "LineSegment3D",
            shape_b: "SphericalSurface3D",
            required: true,
            symmetric: false,
            cardinality: Some(Cardinality::Multiple),
            entrypoint_a_to_b: Some("line_segment3d_spherical_surface3d_intersections"),
            entrypoint_b_to_a: None,
        },
    ]
}
