use super::{Dimension, MatrixEntry, Operation};

pub(super) fn entries() -> Vec<MatrixEntry> {
    vec![
        MatrixEntry {
            id: "3d:segment-point:distance",
            dimension: Dimension::D3,
            operation: Operation::Distance,
            shape_a: "LineSegment3D",
            shape_b: "Point3D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("line_segment3d_point3d_distance"),
            entrypoint_b_to_a: Some("point3d_line_segment3d_distance"),
        },
        MatrixEntry {
            id: "3d:point-segment:distance",
            dimension: Dimension::D3,
            operation: Operation::Distance,
            shape_a: "Point3D",
            shape_b: "LineSegment3D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("point3d_line_segment3d_distance"),
            entrypoint_b_to_a: Some("line_segment3d_point3d_distance"),
        },
        MatrixEntry {
            id: "3d:infinite_line-point:distance",
            dimension: Dimension::D3,
            operation: Operation::Distance,
            shape_a: "InfiniteLine3D",
            shape_b: "Point3D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("infinite_line3d_point3d_distance"),
            entrypoint_b_to_a: Some("point3d_infinite_line3d_distance"),
        },
        MatrixEntry {
            id: "3d:point-infinite_line:distance",
            dimension: Dimension::D3,
            operation: Operation::Distance,
            shape_a: "Point3D",
            shape_b: "InfiniteLine3D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("point3d_infinite_line3d_distance"),
            entrypoint_b_to_a: Some("infinite_line3d_point3d_distance"),
        },
        MatrixEntry {
            id: "3d:infinite_line-infinite_line:distance",
            dimension: Dimension::D3,
            operation: Operation::Distance,
            shape_a: "InfiniteLine3D",
            shape_b: "InfiniteLine3D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("infinite_line3d_infinite_line3d_distance"),
            entrypoint_b_to_a: Some("infinite_line3d_infinite_line3d_distance"),
        },
        MatrixEntry {
            id: "3d:plane-point:distance",
            dimension: Dimension::D3,
            operation: Operation::Distance,
            shape_a: "Plane3D",
            shape_b: "Point3D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("plane3d_point3d_distance"),
            entrypoint_b_to_a: Some("point3d_plane3d_distance"),
        },
        MatrixEntry {
            id: "3d:point-plane:distance",
            dimension: Dimension::D3,
            operation: Operation::Distance,
            shape_a: "Point3D",
            shape_b: "Plane3D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("point3d_plane3d_distance"),
            entrypoint_b_to_a: Some("plane3d_point3d_distance"),
        },
        MatrixEntry {
            id: "3d:ray-point:distance",
            dimension: Dimension::D3,
            operation: Operation::Distance,
            shape_a: "Ray3D",
            shape_b: "Point3D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("ray3d_point3d_distance"),
            entrypoint_b_to_a: Some("point3d_ray3d_distance"),
        },
        MatrixEntry {
            id: "3d:point-ray:distance",
            dimension: Dimension::D3,
            operation: Operation::Distance,
            shape_a: "Point3D",
            shape_b: "Ray3D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("point3d_ray3d_distance"),
            entrypoint_b_to_a: Some("ray3d_point3d_distance"),
        },
        MatrixEntry {
            id: "3d:circle-point:distance",
            dimension: Dimension::D3,
            operation: Operation::Distance,
            shape_a: "Circle3D",
            shape_b: "Point3D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("circle3d_point3d_distance"),
            entrypoint_b_to_a: Some("point3d_circle3d_distance"),
        },
        MatrixEntry {
            id: "3d:point-circle:distance",
            dimension: Dimension::D3,
            operation: Operation::Distance,
            shape_a: "Point3D",
            shape_b: "Circle3D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("point3d_circle3d_distance"),
            entrypoint_b_to_a: Some("circle3d_point3d_distance"),
        },
        MatrixEntry {
            id: "3d:nurbs_3d-point:distance",
            dimension: Dimension::D3,
            operation: Operation::Distance,
            shape_a: "NurbsCurve3D",
            shape_b: "Point3D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("nurbscurve3d_point3d_distance"),
            entrypoint_b_to_a: Some("point3d_nurbscurve3d_distance"),
        },
        MatrixEntry {
            id: "3d:point-nurbs_3d:distance",
            dimension: Dimension::D3,
            operation: Operation::Distance,
            shape_a: "Point3D",
            shape_b: "NurbsCurve3D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("point3d_nurbscurve3d_distance"),
            entrypoint_b_to_a: Some("nurbscurve3d_point3d_distance"),
        },
        MatrixEntry {
            id: "3d:nurbs_3d-linesegment:distance",
            dimension: Dimension::D3,
            operation: Operation::Distance,
            shape_a: "NurbsCurve3D",
            shape_b: "LineSegment3D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("nurbscurve3d_linesegment3d_distance"),
            entrypoint_b_to_a: Some("linesegment3d_nurbscurve3d_distance"),
        },
        MatrixEntry {
            id: "3d:linesegment-nurbs_3d:distance",
            dimension: Dimension::D3,
            operation: Operation::Distance,
            shape_a: "LineSegment3D",
            shape_b: "NurbsCurve3D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("linesegment3d_nurbscurve3d_distance"),
            entrypoint_b_to_a: Some("nurbscurve3d_linesegment3d_distance"),
        },
        MatrixEntry {
            id: "3d:nurbs_3d-ray:distance",
            dimension: Dimension::D3,
            operation: Operation::Distance,
            shape_a: "NurbsCurve3D",
            shape_b: "Ray3D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("nurbscurve3d_ray3d_distance"),
            entrypoint_b_to_a: Some("ray3d_nurbscurve3d_distance"),
        },
        MatrixEntry {
            id: "3d:ray-nurbs_3d:distance",
            dimension: Dimension::D3,
            operation: Operation::Distance,
            shape_a: "Ray3D",
            shape_b: "NurbsCurve3D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("ray3d_nurbscurve3d_distance"),
            entrypoint_b_to_a: Some("nurbscurve3d_ray3d_distance"),
        },
        MatrixEntry {
            id: "3d:nurbs_3d-infinite_line:distance",
            dimension: Dimension::D3,
            operation: Operation::Distance,
            shape_a: "NurbsCurve3D",
            shape_b: "InfiniteLine3D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("nurbscurve3d_infinite_line3d_distance"),
            entrypoint_b_to_a: Some("infinite_line3d_nurbscurve3d_distance"),
        },
        MatrixEntry {
            id: "3d:infinite_line-nurbs_3d:distance",
            dimension: Dimension::D3,
            operation: Operation::Distance,
            shape_a: "InfiniteLine3D",
            shape_b: "NurbsCurve3D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("infinite_line3d_nurbscurve3d_distance"),
            entrypoint_b_to_a: Some("nurbscurve3d_infinite_line3d_distance"),
        },
        MatrixEntry {
            id: "3d:nurbs_3d-circle:distance",
            dimension: Dimension::D3,
            operation: Operation::Distance,
            shape_a: "NurbsCurve3D",
            shape_b: "Circle3D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("nurbscurve3d_circle3d_distance"),
            entrypoint_b_to_a: Some("circle3d_nurbscurve3d_distance"),
        },
        MatrixEntry {
            id: "3d:circle-nurbs_3d:distance",
            dimension: Dimension::D3,
            operation: Operation::Distance,
            shape_a: "Circle3D",
            shape_b: "NurbsCurve3D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("circle3d_nurbscurve3d_distance"),
            entrypoint_b_to_a: Some("nurbscurve3d_circle3d_distance"),
        },
        MatrixEntry {
            id: "3d:nurbs_3d-plane:distance",
            dimension: Dimension::D3,
            operation: Operation::Distance,
            shape_a: "NurbsCurve3D",
            shape_b: "Plane3D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("nurbscurve3d_plane3d_distance"),
            entrypoint_b_to_a: Some("plane3d_nurbscurve3d_distance"),
        },
        MatrixEntry {
            id: "3d:plane-nurbs_3d:distance",
            dimension: Dimension::D3,
            operation: Operation::Distance,
            shape_a: "Plane3D",
            shape_b: "NurbsCurve3D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("plane3d_nurbscurve3d_distance"),
            entrypoint_b_to_a: Some("nurbscurve3d_plane3d_distance"),
        },
        MatrixEntry {
            id: "3d:nurbs_3d-spherical_solid:distance",
            dimension: Dimension::D3,
            operation: Operation::Distance,
            shape_a: "NurbsCurve3D",
            shape_b: "SphericalSolid3D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("nurbscurve3d_spherical_solid3d_distance"),
            entrypoint_b_to_a: Some("spherical_solid3d_nurbscurve3d_distance"),
        },
        MatrixEntry {
            id: "3d:spherical_solid-nurbs_3d:distance",
            dimension: Dimension::D3,
            operation: Operation::Distance,
            shape_a: "SphericalSolid3D",
            shape_b: "NurbsCurve3D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("spherical_solid3d_nurbscurve3d_distance"),
            entrypoint_b_to_a: Some("nurbscurve3d_spherical_solid3d_distance"),
        },
        MatrixEntry {
            id: "3d:nurbs_3d-ellipsoidal_solid:distance",
            dimension: Dimension::D3,
            operation: Operation::Distance,
            shape_a: "NurbsCurve3D",
            shape_b: "EllipsoidalSolid3D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("nurbscurve3d_ellipsoidal_solid3d_distance"),
            entrypoint_b_to_a: Some("ellipsoidal_solid3d_nurbscurve3d_distance"),
        },
        MatrixEntry {
            id: "3d:ellipsoidal_solid-nurbs_3d:distance",
            dimension: Dimension::D3,
            operation: Operation::Distance,
            shape_a: "EllipsoidalSolid3D",
            shape_b: "NurbsCurve3D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("ellipsoidal_solid3d_nurbscurve3d_distance"),
            entrypoint_b_to_a: Some("nurbscurve3d_ellipsoidal_solid3d_distance"),
        },
        MatrixEntry {
            id: "3d:nurbs_3d-cylindrical_solid:distance",
            dimension: Dimension::D3,
            operation: Operation::Distance,
            shape_a: "NurbsCurve3D",
            shape_b: "CylindricalSolid3D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("nurbscurve3d_cylindrical_solid3d_distance"),
            entrypoint_b_to_a: Some("cylindrical_solid3d_nurbscurve3d_distance"),
        },
        MatrixEntry {
            id: "3d:cylindrical_solid-nurbs_3d:distance",
            dimension: Dimension::D3,
            operation: Operation::Distance,
            shape_a: "CylindricalSolid3D",
            shape_b: "NurbsCurve3D",
            required: true,
            symmetric: true,
            cardinality: None,
            entrypoint_a_to_b: Some("cylindrical_solid3d_nurbscurve3d_distance"),
            entrypoint_b_to_a: Some("nurbscurve3d_cylindrical_solid3d_distance"),
        },
    ]
}
