[package]
name = "render"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.30.13"
wgpu = "29.0.1"
tracing = "0.1"
bytemuck = "1.23.2"
pollster.workspace = true
viewmodel = { path = "../../viewmodel/converter" }
analysis = { path = "../../foundation/analysis" }
logging_foundation = { path = "../../foundation/logging_foundation" }
viewmodel-graphics = { path = "../../viewmodel/graphics" }
