[package]
name = "cam_sim"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
analysis = { path = "../../foundation/analysis" }
cam_core = { path = "../cam_core" }
geo_algorithms = { path = "../geo_algorithms" }
job_manager_core = { path = "../job_manager_core" }
