[package]
name = "analysis"
version = "0.1.0"
edition = "2021"
description = "Numerical analysis and geometric sampling for RedRing CAD/CAM"
license = "MIT"

[dependencies]
# 純粋な数値計算のため、外部クレートに依存しない

[dev-dependencies]
approx = "0.5"

[features]
default = []
